mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('users.urls')),
    path('', include('products.urls')),
    path('', include('swaps.urls')),
    path('checkout/', include('checkout.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/products/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView
)


urlpatterns = [
    path('feed/', login_required(ProductListView.as_view()), name='product-feed'),
    path('product/<int:pk>/', login_required(ProductDetailView.as_view()), name='product-detail'),
    path('product/new/', login_required(ProductCreateView.as_view()), name='product-create'),
    path('product/<int:pk>/update/', login_required(ProductUpdateView.as_view()), name='product-update'),
    path('product/<int:pk>/delete/', login_required(ProductDeleteView.as_view()), name='product-delete')
]

mysite/swaps/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import MakeOfferListView, cancel_offers, ReviewOffersListView, review_single_offer

urlpatterns = [
    path('make_offer/<int:product_id>/', login_required(MakeOfferListView.as_view()), name='make-offer'),
    path('cancel_offers/<int:product_id>', login_required(cancel_offers), name='cancel-offers'),
    path('review_offers/<int:product_id>/', login_required(ReviewOffersListView.as_view()), name='review-offers'),
    path('review_offer/<int:offered_product_id>/<int:users_product_id>/', review_single_offer, name='review-single-offer')
]

mysite/products/models.py
import math
import datetime
import os
from io import BytesIO

from django.db import models
from django.db.models import Q
from django.core.files import File
from django.apps import apps
from django.utils import timezone
from django_enumfield import enum
from django.contrib.auth.models import User
from django.urls import reverse

from PIL import Image

from swaps.model_enums import SwapStatus
from sizes.models import Size
from sizes.model_enums import GenderOptions
from .model_enums import ProductStatus, ClothingType


class Product(models.Model):

    name = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    gender = enum.EnumField(GenderOptions, default=GenderOptions.UNISEX)
    clothing_type = enum.EnumField(ClothingType, default=ClothingType.T_SHIRT)
    size = models.ForeignKey(Size, null=True, on_delete=models.SET_NULL)
    image = models.ImageField(upload_to='product_pics')
    image2 = models.ImageField(upload_to='product_pics', blank=True)
    image3 = models.ImageField(upload_to='product_pics', blank=True)
    image4 = models.ImageField(upload_to='product_pics', blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    status = enum.EnumField(ProductStatus, default=ProductStatus.LIVE)

    # Will store image crop dims - filled in ProductCreateView Form
    crop_dimensions_image = None
    crop_dimensions_image2 = None
    crop_dimensions_image3 = None
    crop_dimensions_image4 = None

    def __str__(self):
        return f'ID: {self.id} - {self.name} - status:{self.status.name}'

    def get_absolute_url(self):
        return reverse('product-detail', kwargs={'pk': self.pk})

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        # FIXME will the lines below cause issues if we update the product??
        self.image = self.crop_resize_rename_image(self.image, self.crop_dimensions_image, 'image')
        self.image2 = self.crop_resize_rename_image(self.image2, self.crop_dimensions_image2, 'image2')
        self.image3 = self.crop_resize_rename_image(self.image3, self.crop_dimensions_image3, 'image3')
        self.image4 = self.crop_resize_rename_image(self.image4, self.crop_dimensions_image4, 'image4')
        super(Product, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def crop_resize_rename_image(self, img_field, crop_dimensions, output_filename_prefix):

        if (not bool(img_field)) or (crop_dimensions is None):
            return img_field  # TODO probably log here if img is not None but crop dims are

        pil_img = Image.open(img_field)
        img_format = pil_img.format  # note - important this comes above rotation

        # Rotate mobile upload images that otherwise get wrong orientation
        exif = pil_img._getexif()
        orientation_key = 274  # cf ExifTags
        if exif and orientation_key in exif:
            orientation = exif[orientation_key]
            rotate_values = {
                3: Image.ROTATE_180,
                6: Image.ROTATE_270,
                8: Image.ROTATE_90
            }
            if orientation in rotate_values:
                pil_img = pil_img.transpose(rotate_values[orientation])

        pil_img = pil_img.crop(crop_dimensions)  # crop image
        pil_img = pil_img.resize((512, 512))  # resize image
        thumb_io = BytesIO()  # create a BytesIO object
        pil_img.save(thumb_io, img_format)  # save image to BytesIO object

        _, file_extension = os.path.splitext(self.image.name)
        new_filename = self.date_posted.strftime(f'{output_filename_prefix}_%d_%m_%Y_%H_%M_%S{file_extension}')
        image = File(thumb_io, name=new_filename)  # create a django friendly File object

        return image

    @property
    def number_of_offers(self):
        """ Returns number of pending offers currently for this product

        Note - using apps.get_model() to avoid circular import
        """
        Swap = apps.get_model('swaps', 'Swap')
        return len(Swap.objects.filter(desired_product=self, status=SwapStatus.PENDING_REVIEW))

    @property
    def hours_left_to_checkout(self):
        """ Returns the time left to complete checkout of this product before status automatically reverts back to
        LIVE and the Swap gets cancelled
        """
        Swap = apps.get_model('swaps', 'Swap')
        hours_left_to_checkout = None
        if self.status == ProductStatus.PENDING_CHECKOUT:
            swap = Swap.objects.get((Q(offered_product=self) | Q(desired_product=self))
                                    & Q(status=SwapStatus.PENDING_CHECKOUT))
            hours_left_to_checkout = swap.hours_left_to_checkout
        return hours_left_to_checkout

mysite/products/forms.py
from django import forms
from .models import Product


class ProductCreateForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['image', 'image2', 'image3', 'image4', 'name', 'description', 'gender', 'clothing_type', 'size']
        widgets = {'description': forms.Textarea(attrs={'rows': 4, 'placeholder': 'e.g only worn a few times, true to size'}),
                   'name': forms.TextInput(attrs={'placeholder': 'e.g. White Nike Jumper'})}

    def save(self, commit=True):
        self.instance.crop_dimensions_image = self.extract_crop_dims_from_post_data('crop_dimensions_image')
        self.instance.crop_dimensions_image2 = self.extract_crop_dims_from_post_data('crop_dimensions_image2')
        self.instance.crop_dimensions_image3 = self.extract_crop_dims_from_post_data('crop_dimensions_image3')
        self.instance.crop_dimensions_image4 = self.extract_crop_dims_from_post_data('crop_dimensions_image4')
        return super(ProductCreateForm, self).save(commit=True)

    def extract_crop_dims_from_post_data(self, field_name):
        try:
            dims = [int(dim) for dim in self.data.get(field_name).split(',')]
        except ValueError:
            dims = None  # means no image was uploaded for this field

        return dims


class ProductUpdateForm(forms.ModelForm):

    class Meta:
        model = Product

        fields = ['name', 'description', 'gender', 'clothing_type', 'size']
        widgets = {'description': forms.Textarea(attrs={'rows': 4})}

mysite/products/views.py
import random
from datetime import datetime, timedelta

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Product, ProductStatus
from sizes.model_enums import GenderOptions
from swaps.models import Swap, SwapStatus
from .forms import ProductCreateForm, ProductUpdateForm


class ProductListView(ListView):
    model = Product
    template_name = 'products/feed.html'
    context_object_name = 'products'
    paginate_by = 36
    feed_order_expiry_mins = 30

    def get_queryset(self):
        """ Returns all LIVE (non-matched) products the current user does not own and hasn't already made an offer for"""

        # 1) Filter for LIVE products only
        filtered_products = Product.objects.filter(status=ProductStatus.LIVE)

        # 2) Exclude products current user owns
        filtered_products = filtered_products.exclude(owner=self.request.user)

        # 3) Filter by current users gender preference
        users_gender_preference = self.request.user.profile.gender_preference
        if users_gender_preference not in [GenderOptions.UNISEX, None]:
            filtered_products = filtered_products.filter(gender__in=[users_gender_preference, GenderOptions.UNISEX])

        # 4) Exclude products current user has made offer on already
        users_offers = Swap.objects.filter(offered_product__owner__exact=self.request.user)
        already_offered_on_product_ids = set([offer.desired_product.id for offer in users_offers])
        filtered_products = filtered_products.exclude(id__in=already_offered_on_product_ids)

        # 5) shuffle
        filtered_products = list(filtered_products)
        random_seed = self.get_random_seed()
        random.Random(random_seed).shuffle(filtered_products)

        return filtered_products

    def get_random_seed(self):
        time_format = '%d/%m/%y %H:%M:%S'
        random_seed = self.request.session.get('random_seed')
        random_seed_expiry_str = self.request.session.get('random_seed_expiry')
        if (not random_seed) or (datetime.strptime(random_seed_expiry_str, time_format) < datetime.now()):
            random_seed = random.randint(0, 100)
            self.request.session['random_seed'] = random_seed
            self.request.session['random_seed_expiry'] = datetime.strftime(datetime.now() +
                                                                           timedelta(minutes=self.feed_order_expiry_mins), time_format)
        return random_seed


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        """
        Overriding to add 'button_text' and 'button_redirect_url' to context.

        This is used in template in the main 'call to action' button which can be on of 4 things depending on status.
        """
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        product = self.object
        button_text = ''
        button_redirect_url = '#'
        if product.owner == self.request.user:
            if product.status == ProductStatus.LIVE:
                button_text = f'Review {product.number_of_offers} Offers'
                button_redirect_url = reverse_lazy('review-offers', kwargs={'product_id': product.id})
            elif product.status == ProductStatus.PENDING_CHECKOUT:
                button_text = 'Checkout Now'
                button_redirect_url = reverse_lazy('checkout', kwargs={'product_id': product.id})
        else:
            # get QuerySet of offers made by current user for this product
            users_offers_on_product = Swap.objects.filter(offered_product__owner=self.request.user,
                                                          desired_product=product,
                                                          status=SwapStatus.PENDING_REVIEW)
            if users_offers_on_product:
                button_text = f'Cancel {len(users_offers_on_product)} Offers'
                button_redirect_url = reverse_lazy('cancel-offers', kwargs={'product_id': product.id})
            else:
                button_text = 'Make Offer'
                button_redirect_url = reverse_lazy('make-offer', kwargs={'product_id': product.id})

        context['button_text'] = button_text
        context['button_redirect_url'] = button_redirect_url

        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductCreateForm
    template_name = 'products/create_form.html'
    success_url = reverse_lazy(viewname='profile-your-items')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(ProductCreateView, self).form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductUpdateForm
    template_name = 'products/update_form.html'
    success_url = reverse_lazy(viewname='profile-your-items')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def test_func(self):
        product = self.get_object()
        if self.request.user == product.owner:
            return True
        return False


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy(viewname='profile-your-items')

    def test_func(self):
        product = self.get_object()
        if self.request.user == product.owner:
            return True
        return False

mysite/products/templates/products/_base_feed.html
<! Used as a base component for product feed and profile feed - exposes single_product block to be extended>
{% load user_agents %}
<div>
    <div class="row">
        {% for product in products %}
            <div class="col-4 col-md-3 custom-gutter">
                {% block single_product %} {% endblock %}
            </div>
        {% endfor %}
    </div>
</div>
<script>
    $(document).ready(function() {
        let images = $('.grid-item, .num-offers-icon, .offer-status-overlay');
        let i
        for (i=0; i<images.length; i++){
            images[i].style.visibility = 'visible'
        }
    });
</script>

mysite/products/templates/products/_base_product_detail.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
        <div class="row">
            <div class="col-12 col-md-6" style="margin-top: 10px; margin-bottom: 10px">
                <!-- The slideshow -->
                <div id="demo" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="{{ product.image.url }}" width="100%">
                        </div>
                        {% if product.image2 %}
                            <div class="carousel-item">
                                <img src="{{ product.image2.url }}" width="100%">
                            </div>
                        {% endif %}
                        {% if product.image3 %}
                            <div class="carousel-item">
                                <img src="{{ product.image3.url }}" width="100%">
                            </div>
                        {% endif %}
                        {% if product.image4 %}
                            <div class="carousel-item">
                                <img src="{{ product.image4.url }}" width="100%">
                            </div>
                        {% endif %}
                    </div>

                     {% if product.image2.url or product.image3.url or product.image4.url %}
                        <!-- Left and right controls -->
                        <a class="carousel-control-prev" href="#demo" data-slide="prev">
                            <span class="carousel-control-prev-icon"></span>
                        </a>
                        <a class="carousel-control-next" href="#demo" data-slide="next">
                            <span class="carousel-control-next-icon"></span>
                        </a>
                    {% endif %}
                </div>
            </div>

            <div class="col-12 col-md-6"  style="margin-top: 10px; margin-bottom: 10px">
                <div class="product-detail-container">

                    {% block edit_delete_icons %}
                    {% endblock edit_delete_icons %}

                    <div class="item-owner-container" style="padding: 20px 40px; border-bottom: 1px solid lightgray">
                        <a href="{% url "profile-other-user" product.owner.id %}">
                            <img class="rounded-circle checkout-profile-pic" src="{{ product.owner.profile.image.url }}"
                             style="width: 50px; height: 50px;">
                        </a>
                        <h6 class="checkout-username">{{ product.owner.username }} </h6>
                    </div>

                      <div style="text-align: center; margin-top: 5%">
                          <h2 class="item-name">{{ product.name }}</h2>
                          <h6 class="item-size">Size: {{ product.size }}</h6>
                          {#              <h6 class="article-title">Status: {{ product.status.label }}</h6>#}
                          <p class="item-description">{{ product.description }}</p>
                      </div>

                      <div style="bottom: 10px; text-align: center">
                          <!-- this block will be filled with the action button/form e.g. 'make offer' etc. -->
                          {% block product_detail_action %}
                          {% endblock product_detail_action %}
                      </div>

                </div>

            </div>
        </div>
{% endblock content %}

mysite/products/templates/products/_product_feed.html
{% extends "products/_base_feed.html" %}
{% block single_product %}
  <div class="product-container">
      <a href="{% url 'product-detail' product.id %}" style="width: 100%">
        <img class="grid-item thumbnail" src="{{ product.image.url }}" style="width: 100%; visibility: hidden">
      </a>
      <a class="num-offers-icon" style="visibility: hidden" href="{% url 'product-detail' product.id %}"> {{ product.number_of_offers }}</a>
  </div>
{% endblock %}

mysite/products/templates/products/create_form.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="row border-bottom mb-4" style="margin-bottom: 5%">
        <h4> Upload Item </h4>
    </div>

    <div>
              <!-- Container for croppie - contains placeholder image at start -->
              <!-- NOTE- do NOT change the IDs carelessly here as they are used for the image cropping! -->
              <!-- Warning - do NOT place this inside form as click on upload image will bubble to other form fields -->
              <div class="row">
                  <div class="col-12 col-md-6">
                    <div id="croppie_container_image" class="croppie-div">
                          <button  id="upload_placeholder_image" onclick="triggerImageUpload(this);">
                                <img src="{% static "assets/upload_placeholder_image_1.png" %}" style="width: 100%; height: 100%">
                          </button>
                      </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div id="croppie_container_image2" class="croppie-div">
                          <button  id="upload_placeholder_image2" onclick="triggerImageUpload(this);">
                                <img src="{% static "assets/upload_placeholder_image_2.png" %}" style="width: 100%; height: 100%">
                          </button>
                      </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div id="croppie_container_image3" class="croppie-div">
                          <button  id="upload_placeholder_image3" onclick="triggerImageUpload(this);">
                                <img src="{% static "assets/upload_placeholder_image_3.png" %}" style="width: 100%; height: 100%">
                          </button>
                      </div>
                  </div>
                  <div class="col-12 col-md-6">
                    <div id="croppie_container_image4" class="croppie-div">
                          <button  id="upload_placeholder_image4"  onclick="triggerImageUpload(this);">
                                <img src="{% static "assets/upload_placeholder_image_4.png" %}" style="width: 100%; height: 100%">
                          </button>
                      </div>
                  </div>
              </div>

        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}


            <fieldset class="form-group">

                <div class="django-form-container">
                    {{ form|crispy }}
                </div>

                <input id="crop_dimensions_image" name="crop_dimensions_image" style="display: none">
                <input id="crop_dimensions_image2" name="crop_dimensions_image2" style="display: none">
                <input id="crop_dimensions_image3" name="crop_dimensions_image3" style="display: none">
                <input id="crop_dimensions_image4" name="crop_dimensions_image4" style="display: none">

            </fieldset>

            <!-- Display form errors-->
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error }}</strong>
                    </div>
                {% endfor %}
            {% endif %}

            <div style="text-align: center; margin: 5% 20% 10% 20%">
                <button class="standard-swapdrop-btn" type="submit">Upload</button>
            </div>
        </form>


        <script>

            // hidden upload <input> elements for each image
            let uploadedImage = document.getElementById('id_image');
            let uploadedImage2 = document.getElementById('id_image2');
            let uploadedImage3 = document.getElementById('id_image3');
            let uploadedImage4 = document.getElementById('id_image4');

            // Call the processFile every time the chosen image is changed
            uploadedImage.addEventListener("change", processFile);
            uploadedImage2.addEventListener("change", processFile)
            uploadedImage3.addEventListener("change", processFile)
            uploadedImage4.addEventListener("change", processFile)

            // Each time crop changes store the crop dimensions in a hidden input
            $('#croppie_container_image').on('update.croppie', getCropDimensions);
            $('#croppie_container_image2').on('update.croppie', getCropDimensions);
            $('#croppie_container_image3').on('update.croppie', getCropDimensions);
            $('#croppie_container_image4').on('update.croppie', getCropDimensions);
        </script>



        <script>
            // Hide sizes that are only applicable to the gender not selected
            $('#id_gender').on('change', function() {
                let selectedValue = $("#id_gender").val();
                let selectedGender = $("#id_gender").find("option").filter(function() {return $(this).val() === selectedValue;}).text()
                let menSizes = $("#id_size").find("option").filter(function () { return $(this).html().includes("Men"); });
                let womenSizes = $("#id_size").find("option").filter(function () { return $(this).html().includes("Women"); });
                if (selectedGender === 'Menswear'){
                    menSizes.show();
                    womenSizes.hide();
                } else if ((selectedGender === 'Womenswear')){
                    menSizes.hide();
                    womenSizes.show();
                } else {
                    // for Unisex
                    menSizes.show();
                    womenSizes.show();
                }
            })
        </script>
    </div>
{% endblock content %}

mysite/products/templates/products/feed.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% load user_agents %}
{% block content %}

    <div>
        <div style="text-align: center">
            <input class="search-bar" type="text" placeholder="🔍">
        </div>

        <div>
            {% include "products/_product_feed.html" %}
        </div>


        <div class="pagination">
        <span class="step-links" style="margin-left: auto; margin-right: auto; margin-top: 5%; margin-bottom: 5%">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
        </div>
    </div>

{% endblock content %}

mysite/products/templates/products/product_confirm_delete.html
{% extends "homepage/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Product</legend>
                <h4>Are you sure you want to delete this product? </h4>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-secondary" href="{% url 'product-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

mysite/products/templates/products/product_detail.html
{% extends "products/_base_product_detail.html" %}
{% load static %}
{% load user_agents %}

{% block edit_delete_icons %}
    {% if product.owner == user %}
        {% if product.status.name == 'LIVE' %}
          <div style="text-align: center">
              <a class="edit-delete-icons" href="{% url 'product-update' product.id %}">
                  <img src="{% static "assets/product_edit_icon.png" %}" style="width: 56px; height: 56px">
              </a>
              <a class="edit-delete-icons" href="{% url 'product-delete' product.id %}">
                  <img src="{% static "assets/product_delete_icon.png" %}" style="width: 56px; height: 56px">
              </a>
          </div>
        {% endif %}
    {% endif %}
{% endblock edit_delete_icons %}

{% block product_detail_action %}
    <!-- Button text and redirect url determined in view -->
     {% if button_text %}
          <a class="standard-swapdrop-btn" href="{{ button_redirect_url }}"> {{ button_text }} </a>
    {% endif %}
{% endblock product_detail_action %}

mysite/products/templates/products/product_form.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update Product</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock content %}

mysite/products/templates/products/update_form.html
{% extends "homepage/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update Product</legend>
                {{ form|crispy }}
            </fieldset>
            <div style="text-align: center; margin: 5% 20% 10% 20%">
                <button class="standard-swapdrop-btn" type="submit">Update</button>
            </div>
        </form>

        <script>
            function changeVisibleSizesByGender(){
                let selectedValue = $("#id_gender").val();
                let selectedGender = $("#id_gender").find("option").filter(function() {return $(this).val() === selectedValue;}).text()
                let menSizes = $("#id_size").find("option").filter(function () { return $(this).html().includes("Men"); });
                let womenSizes = $("#id_size").find("option").filter(function () { return $(this).html().includes("Women"); });
                if (selectedGender === 'Menswear'){
                    menSizes.show();
                    womenSizes.hide();
                } else if ((selectedGender === 'Womenswear')){
                    menSizes.hide();
                    womenSizes.show();
                } else {
                    // for Unisex
                    menSizes.show();
                    womenSizes.show();
                }
            }

            $('#id_gender').on('change', changeVisibleSizesByGender)
            $(document).ready(changeVisibleSizesByGender())

        </script>

    </div>
{% endblock content %}