mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', include('users.urls')),
    path('', include('products.urls')),
    path('', include('swaps.urls')),
    path('checkout/', include('checkout.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/swaps/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import MakeOfferListView, cancel_offers, ReviewOffersListView, review_single_offer

urlpatterns = [
    path('make_offer/<int:product_id>/', login_required(MakeOfferListView.as_view()), name='make-offer'),
    path('cancel_offers/<int:product_id>', login_required(cancel_offers), name='cancel-offers'),
    path('review_offers/<int:product_id>/', login_required(ReviewOffersListView.as_view()), name='review-offers'),
    path('review_offer/<int:offered_product_id>/<int:users_product_id>/', review_single_offer, name='review-single-offer')
]

mysite/users/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

from users.views import register, Login, ProfileYourItemsListView, ProfileOffersMadeListView, profile_other_user, profile_info,  shipping_address_info
from users.forms import UserLoginForm

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', Login.as_view(authentication_form=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name=None), name='logout'),
    path('profile/<int:user_id>/', login_required(profile_other_user), name='profile-other-user'),
    path('profile/', login_required(ProfileYourItemsListView.as_view()), name='profile-your-items'),
    path('profile/your_items/', login_required(ProfileYourItemsListView.as_view()), name='profile-your-items'),
    path('profile/offers_made/', login_required(ProfileOffersMadeListView.as_view()), name='profile-offers-made'),
    path('profile/info/', login_required(profile_info), name='profile-info'),
    path('profile/address/', login_required(shipping_address_info), name='shipping-address-info')
    ]

mysite/users/models.py
import os
from io import BytesIO

from django.db import models
from django.core.files import File
from django.contrib.auth.models import User
from django_enumfield import enum

from PIL import Image

from sizes.models import Size
from sizes.model_enums import GenderOptions

""" Scroll down for Profile"""


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # 'user' includes: username, password, email address.

    # profile picture
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    bio = models.CharField(max_length=30, null=True, blank=True)

    # shipping address
    house_name_number = models.CharField(max_length=50, blank=True)
    address_line_1 = models.CharField(max_length=50, blank=True)
    address_line_2 = models.CharField(max_length=50, blank=True)
    town_city = models.CharField(max_length=50, blank=True)
    county = models.CharField(max_length=50, blank=True)
    postcode = models.CharField(max_length=10, blank=True)
    contact_number = models.CharField(max_length=13, blank=True)

    # clothing preferences
    # Note - this has been designed to allow the user to view a range of sizes rather than limiting them to select only one size
    gender_preference = enum.EnumField(GenderOptions, blank=True, null=True)  # menswear, womenswear
    sizes = models.ManyToManyField(Size)

    # Will store image crop dims - filled in ProductCreateView Form
    crop_dimensions_image = None

    def __str__(self):
        return f'{self.user.username}'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.image = self.crop_resize_rename_image(self.image, self.crop_dimensions_image)
        super(Profile, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def crop_resize_rename_image(self, img_field, crop_dimensions):

        if (not bool(img_field)) or (crop_dimensions is None):
            return img_field  # TODO probably log here if img is not None but crop dims are

        pil_img = Image.open(img_field)
        img_format = pil_img.format  # note - important this comes above rotation

        # Rotate mobile upload images that otherwise get wrong orientation
        exif = pil_img._getexif()
        orientation_key = 274  # cf ExifTags
        if exif and orientation_key in exif:
            orientation = exif[orientation_key]
            rotate_values = {
                3: Image.ROTATE_180,
                6: Image.ROTATE_270,
                8: Image.ROTATE_90
            }
            if orientation in rotate_values:
                pil_img = pil_img.transpose(rotate_values[orientation])

        pil_img = pil_img.crop(crop_dimensions)  # crop image
        pil_img = pil_img.resize((512, 512))  # resize image
        thumb_io = BytesIO()  # create a BytesIO object
        pil_img.save(thumb_io, img_format)  # save image to BytesIO object

        image = File(thumb_io, name=self.image.name)  # create a django friendly File object

        return image

mysite/users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from users.validators import is_in_chichester


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'email'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'username'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'confirm password'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        for fieldname in ['username', 'email', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


class UserPostcodeForm(forms.ModelForm):
    postcode = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'postcode'}),
                               validators=[is_in_chichester])

    class Meta:
        model = Profile
        fields = ['postcode']


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password'}))


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image', 'bio']

    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        for fieldname in ['image', 'bio']:
            self.fields[fieldname].help_text = None

    def save(self, commit=True):
        self.instance.crop_dimensions_image = self.extract_crop_dims_from_post_data('crop_dimensions_image')
        return super(ProfileUpdateForm, self).save(commit=True)

    def extract_crop_dims_from_post_data(self, field_name):
        try:
            dims = [int(dim) for dim in self.data.get(field_name).split(',')]
        except ValueError:
            dims = None  # means no image was uploaded for this field
        return dims


class ShippingAddressUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['image', 'bio', 'user', 'gender_preference', 'sizes']  # ie include all fields except image (house_name_number, address...)
        labels = {'house_name_number': 'House Name/Number',  # django automates this. override bad ones.
                  'address_line_1': 'Address Line 1',
                  'address_line_2': 'Address Line 2',
                  'town_city': 'Town/City',
                  'contact_number': 'Contact Number'
                  }

    def __init__(self, *args, **kwargs):
        super(ShippingAddressUpdateForm, self).__init__(*args, **kwargs)
        self.fields['house_name_number'].required = True
        self.fields['address_line_1'].required = True
        self.fields['town_city'].required = True
        self.fields['postcode'].required = True
        self.fields['contact_number'].required = True

    def is_initial_valid(self):
        """
        Returns True if initial values passed into form are already valid.

        Used to determine whether or not we need to redirect user to shipping address form after a match.

        Returns
        -------
        is_valid: bool
        """
        try:
            for field_name, field in self.fields.items():
                field.validate(value=self.initial.get(field_name))
        except ValidationError:
            return False

        return True

mysite/users/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views
from django.contrib.auth import authenticate, login
from django.views.generic import (
    ListView
)


from products.models import Product
from swaps.models import Swap, SwapStatus
from sizes.models import Size
from sizes.model_enums import GenderOptions, SizeTypes
from users.forms import UserRegisterForm, UserPostcodeForm, UserUpdateForm, ProfileUpdateForm, ShippingAddressUpdateForm
from users.models import Profile


def register(request):
    if request.method == 'POST':
        user_form = UserRegisterForm(request.POST)
        postcode_form = UserPostcodeForm(request.POST)
        if user_form.is_valid() and postcode_form.is_valid():
            # Create new user and profile
            user = user_form.save()
            # Note - there's probably an easier way of doing below
            profile = Profile.objects.get(user=user)
            profile.postcode = postcode_form.cleaned_data.get('postcode')
            profile.save(update_fields=['postcode'])

            # Automatically log user in
            user = authenticate(username=user_form.cleaned_data['username'],
                                password=user_form.cleaned_data['password1'])
            login(request, user)
            messages.success(request, f'Welcome to Swapdrop - please select your preferences below')
            return redirect('profile-info')
    else:
        user_form = UserRegisterForm()
        postcode_form = UserPostcodeForm()

    template = 'users/register_mobile.html' if request.user_agent.is_mobile else 'users/register.html'
    return render(request, template, {'user_form': user_form, 'postcode_form': postcode_form})


class Login(auth_views.LoginView):

    def __init__(self, *args, **kwargs):
        """ Overriding base LoginView to make template name different for mobile/desktop"""
        super(Login, self).__init__(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.template_name = 'users/login_mobile.html' if self.request.user_agent.is_mobile else 'users/login.html'
        return super(Login, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.template_name = 'users/login_mobile.html' if self.request.user_agent.is_mobile else 'users/login.html'
        return super(Login, self).post(request, *args, **kwargs)


class ProfileYourItemsListView(ListView):
    model = Product
    template_name = 'users/profile_your_items.html'
    context_object_name = 'products'
    ordering = ['-date_posted']

    def get(self, request, *args, **kwargs):
        """ """
        # Check for and process and timed-out swaps belonging to this user TODO move this logic somewhere else
        users_pending_swaps = Swap.objects.filter((Q(offered_product__owner=self.request.user) | Q(desired_product__owner=self.request.user))
                                                  & Q(status=SwapStatus.PENDING_CHECKOUT))
        for swap in users_pending_swaps:
            if swap.hours_left_to_checkout == 0:
                try:
                    swap.timeout_reached()
                except Exception as err:
                    print(f'Warning! - following exception was raised in timeout_reached(): {err}')
        return super(ProfileYourItemsListView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        """ Returns all products owned by currently logged in user"""
        all_products = super(ProfileYourItemsListView, self).get_queryset()
        users_products = all_products.filter(owner=self.request.user)
        return users_products


class ProfileOffersMadeListView(ListView):
    model = Product
    template_name = 'users/profile_offers_made.html'
    context_object_name = 'products'
    ordering = ['-date_posted']

    def get_queryset(self):
        """ Return all products that currently logged in user has made an offer on"""
        offers_made = Swap.objects.filter(offered_product__owner=self.request.user, status=SwapStatus.PENDING_REVIEW)
        # making unique list because there can be multiple offers on the same product
        products_offered_on = list(set([offer.desired_product for offer in offers_made]))
        return products_offered_on


def profile_info(request):
    if request.method == 'POST':

        # Process gender preference
        selected_gender_value = request.POST.get('gender_preference')
        if selected_gender_value == 'm':
            request.user.profile.gender_preference = GenderOptions.MENSWEAR
        elif selected_gender_value == 'w':
            request.user.profile.gender_preference = GenderOptions.WOMENSWEAR
        request.user.profile.save(update_fields=['gender_preference'])

        # Process size selections
        # combine selected Size ids from each of the three dropdowns
        selected_size_ids = request.POST.getlist('primary_size') + request.POST.getlist('waist_size') + request.POST.getlist('shoe_size')
        selected_size_ids = [int(_id) for _id in selected_size_ids]
        selected_sizes = Size.objects.filter(pk__in=selected_size_ids)
        request.user.profile.sizes.clear()
        request.user.profile.sizes.add(*selected_sizes)

        # Process profile pic update
        form = ProfileUpdateForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated')
            return redirect('profile-your-items')

    else:
        form = ProfileUpdateForm(instance=request.user.profile)

        current_gender_preference = request.user.profile.gender_preference
        current_gender_preference_str = '' if current_gender_preference is None else current_gender_preference.name

        context = {'form': form,
                   'current_gender_preference': current_gender_preference_str,
                   'primary_sizes': Size.objects.filter(size_type=SizeTypes.PRIMARY),
                   'current_primary_size_ids': [str(size.id) for size in request.user.profile.sizes.filter(size_type=SizeTypes.PRIMARY)],
                   'waist_sizes': Size.objects.filter(size_type=SizeTypes.WAIST),
                   'current_waist_size_ids': [str(size.id) for size in request.user.profile.sizes.filter(size_type=SizeTypes.WAIST)],
                   'shoe_sizes': Size.objects.filter(size_type=SizeTypes.SHOE),
                   'current_shoe_size_ids': [str(size.id) for size in request.user.profile.sizes.filter(size_type=SizeTypes.SHOE)]}

        return render(request, 'users/profile_info.html', context=context)


def shipping_address_info(request):

    if request.method == 'POST':
        address_form = ShippingAddressUpdateForm(instance=request.user.profile, data=request.POST)
        if address_form.is_valid():
            address_form.save()
            messages.success(request, 'Your shipping address has been updated')
            return redirect('profile-your-items')

    else:
        address_form = ShippingAddressUpdateForm(instance=request.user.profile)
        context = {'address_form': address_form}
        return render(request, 'users/shipping_address_info.html', context=context)


def profile_other_user(request, user_id):
    """ View for viewing another users profile """
    try:
        user = User.objects.get(id=user_id)
        products = Product.objects.filter(owner=user)
        context = {'other_user': user,
                   'products': products}
        return render(request, template_name='users/profile_other_user.html', context=context)
    except User.DoesNotExist:
        raise Http404('Oops - this user doesn\'t exist')

mysite/users/templates/users/_login_component.html
<div class="signup-container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="signup-legend" >Login</legend>
            {{ form }}
        </fieldset>
        <div class="form-group" style="text-align: center">
            <button class="standard-swapdrop-btn" type="submit">Login</button>
        </div>
    </form>
    <div style="text-align: center">
        <small class="signup-footer">
            Need an account? <a style="color: rgb(255, 59, 0)" href="{% url 'register' %}">Signup</a>
        </small>
    </div>
</div>

mysite/users/templates/users/_offers_made_feed.html
{% extends "products/_base_feed.html" %}
{% block single_product %}
  <div class="product-container">
      <a href="{% url 'product-detail' product.id %}" style="width: 100%">
        <img class="grid-item thumbnail" src="{{ product.image.url }}" style="width: 100%; visibility: hidden">
      </a>
      {% if product.status.label == 'Live' %}
            <a class="num-offers-icon" style="visibility: hidden" href="{% url 'product-detail' product.id %}"> {{ product.number_of_offers }}</a>
      {% else %}
            <a class="offer-status-overlay" style="visibility: hidden" href="{% url 'product-detail' product.id %}"></a>
      {% endif %}
  </div>
{% endblock %}

mysite/users/templates/users/_register_component.html
<div class="signup-container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="signup-legend" >Sign Up</legend>
            {{ postcode_form }}
            <p class="postcode-warning"> Sorry - for now you must have a PO19 postcode to sign up </p>
            {{ user_form }}
        </fieldset>
        <div class="form-group" style="text-align: center">
            <button class="standard-swapdrop-btn" type="submit">Sign Up</button>
        </div>
    </form>
    <div style="text-align: center">
        <small class="signup-footer">
            Already got an account? <a style="color: rgb(255, 59, 0)" href="{% url 'login' %}">Login</a>
        </small>
    </div>

    <script>
        // focus on postcode on load instead of username
        $(document).ready(function () {
            $("#id_postcode").focus()
        })
    </script>

    <script>
        // hide/show postcode warning
        $("#id_postcode").focus(function() {
            $(".postcode-warning").hide();}
            ).blur(function() {
            if (this.value && !this.value.startsWith('PO19')){
            $(".postcode-warning").show();
            console.log('INVALID POSTCODE');
            }
            });
    </script>
</div>

mysite/users/templates/users/_register_login_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,600,800">
    <link rel="stylesheet" type="text/css" href="{% static 'users/main.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'assets/orange_logo_transparent_background.png' %}"/>
    <link rel="apple-touch-icon" type="image/png" href="{% static 'assets/orange_logo_transparent_background.png' %}"/>
    <link rel="icon" type="image/png" href="{% static 'assets/orange_logo_transparent_background.png' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Swapdrop</title>
</head>
<body>
    <div class="signup-background">
        <div class="row" style="width: 100%">
            <div class="col-4">
                <div style="margin-top: 25px">
                    <span class="swapdrop-header"> Swapdrop </span>
                    <img src="{% static "assets/white_logo.png" %}" style="vertical-align: middle; width: 25px">
                </div>
                <img src="{% static "assets/orange_logo_transparent_background.png" %}" style="width: 150%">
            </div>

            <div class="col-4">
                {% block form %}
                {% endblock %}
            </div>

            <div class="col-4 no-gutters">
                <img src="{% static "assets/half_desktop_mockup.png" %}" style="width: 80%; margin-top: 10%; float: right; margin-right: -10%">
            </div>
        </div>
    </div>
</body>
</html>

mysite/users/templates/users/_register_login_base_mobile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,600,800">
    <link rel="stylesheet" type="text/css" href="{% static 'users/main.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'assets/white_logo.png' %}"/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Swapdrop</title>
</head>
<body>
    <div class="signup-background-mobile">
            <div style="text-align: center">
                <h1 class="swapdrop-header-mobile"> Swapdrop </h1>
            </div>
            <div class="row" style="margin-left: 10%; margin-right: 10%">
                {% block form %}
                {% endblock %}
            </div>
    </div>
</body>
</html>

mysite/users/templates/users/_your_items_feed.html
{% extends "products/_base_feed.html" %}
{% block single_product %}
  <div class="product-container">
      <a href="{% url 'product-detail' product.id %}" style="width: 100%">
        <img class="grid-item thumbnail" src="{{ product.image.url }}" style="width: 100%; visibility: hidden">
      </a>

      {% if product.status.label == 'Live' %}
          <a class="num-offers-icon" style="visibility: hidden" href="{% url 'product-detail' product.id %}"> {{ product.number_of_offers }}</a>
      {% else %}
              {% if product.status.label == 'Pending Checkout'%}
                  <a class="offer-status-overlay" style="visibility: hidden" href="{% url 'product-detail' product.id %}">{{ product.hours_left_to_checkout }} hours to checkout</a>
              {% elif product.status.label == 'Checkout Complete'%}
                  <a class="offer-status-overlay" style="visibility: hidden" href="{% url 'product-detail' product.id %}"> Collecting Soon</a>
              {% elif product.status.label == 'Collected'%}
                  <a class="offer-status-overlay" style="visibility: hidden" href="{% url 'product-detail' product.id %}">Collected</a>
              {% elif product.status.label == 'Delivered'%}
                  <a class="offer-status-overlay" style="visibility: hidden" href="{% url 'product-detail' product.id %}">Swapped</a>
              {% endif %}
      {% endif %}


  </div>
{% endblock %}

mysite/users/templates/users/_your_profile_base.html
{% extends "users/_profile_base.html" %}
{% load user_agents %}

{% block profile_pic %}
    <a class="profile-img-btn" data-toggle="tooltip" title="Edit Profile" href="{% url "profile-info" %}">
        <img class="rounded-circle profile-img users-profile-img" src="{{ user.profile.image.url }}">
    </a>
{% endblock profile_pic %}

{% block users_username %}
    <h2 class="profile-username">{{ user.username }}</h2>
{% endblock users_username %}

{% block users_bio %}
        <p class="profile-bio"> {{ user.profile.bio }}</p>
{% endblock users_bio %}

{% block upload_button %}
    <a href="{% url 'product-create' %}">
        <button class="upload-button"> +</button>
    </a>
{% endblock upload_button %}


{% block your_items_offers_made_tab %}
    <div class="row profile-tab-row">
            <div class="col-6 profile-tab-col">
                <a id="your-items-link" style="display: inline-block; width: 80%" href="{% url "profile-your-items" %}">
                    Your items
                </a>
            </div>
            <div class="col-6 profile-tab-col">
                <a id="offers-made-link" style="display: inline-block; width: 80%" href="{% url "profile-offers-made" %}">
                    Offers made
                </a>
            </div>
        </div>

        {{ request.resolver_match.url_name|json_script:"current-url" }}
        <script>
            // add underline to 'your items' or 'offers made' tab depending on url name
            // currentUrlName is defined in base.html
            if (currentUrlName.includes('your-items')) {
                $("#your-items-link").parent().addClass("selected_profile_tab_underline")
            } else if (currentUrlName.includes('offers-made')) {
                $("#offers-made-link").parent().addClass("selected_profile_tab_underline")
            }
        </script>
{% endblock %}

mysite/users/templates/users/login_mobile.html
{% extends "users/_register_login_base_mobile.html" %}
{% block form %}
    {% include "users/_login_component.html" %}
{% endblock %}

mysite/users/templates/users/profile_offers_made.html
{% extends "users/_your_profile_base.html" %}
{% block profile_feed %}
    {% if products %}
        {% include "users/_offers_made_feed.html" %}
    {% else %}
        <div style="text-align: center; margin-top: 50px">
            Items you make offers on will appear here
        </div>
    {% endif %}
{% endblock profile_feed %}

mysite/users/templates/users/profile_other_user.html
{% extends "users/_profile_base.html" %}
<!-- NOTE - other_user is used as variable instead of user here as 'user' always refers to currently logged in user -->
{% block profile_pic %}
    <img class="rounded-circle profile-img" src="{{ other_user.profile.image.url }}">
{% endblock %}

{% block users_username %}
    <h2 class="profile-username">{{ other_user.username }}</h2>
{% endblock users_username %}

{% block users_bio %}
    {% if other_user.profile.bio %}
        <p> {{ other_user.profile.bio }}</p>
    {% endif %}
{% endblock users_bio %}

{% block profile_feed %}
    {% include "users/_other_users_profile_feed.html" %}
{% endblock profile_feed %}

mysite/users/templates/users/profile_your_items.html
{% extends "users/_your_profile_base.html" %}
{% block profile_feed %}
    {% include "users/_your_items_feed.html" %}
{% endblock profile_feed %}

mysite/users/templates/users/register.html
{% extends "users/_register_login_base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block form %}
    {% include "users/_register_component.html" %}
{% endblock form %}

mysite/users/templates/users/register_mobile.html
{% extends "users/_register_login_base_mobile.html" %}
{% block form %}
    {% include "users/_register_component.html" %}
{% endblock %}